<?php
/**
 * @file
 * Install/Uninstall code for the Mosaic Grid module.
 */


/**
 * Add auto caption position options to the configuration file.
 */
function glightbox_update_1100() {
  $config = config('glightbox.settings');
  // Rename caption position parameter.
  $caption_pos = $config->get('ui_descr_position');
  $config->set('ui_caption_pos', $caption_pos);
  $config->clear('ui_descr_position');
  // Add new auto caption position options.
  $config->set('ui_auto_aspect_ratio', 1.3);
  $config->set('ui_auto_horiz_pos', 'bottom');
  $config->set('ui_auto_vert_pos', 'right');
  $config->save();
}
